#  T-tests and P-values

In statistics, t-test is used to test if two data samples have a significant difference between their means. There are two types of t-test:

* **Student's t-test** (a.k.a. independent or uncorrelated t-test). This type of t-test is to compare the samples of **two independent populations** (e.g. test scores of students in two different classes). `scipy` provides the [`ttest_ind`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_ind.html) method to conduct student's t-test.

* **Paired t-test** (a.k.a. dependent or correlated t-test). This type of t-test is to compare the samples of **the same population** (e.g. scores of different tests of students in the same class). `scipy` provides the [`ttest_rel`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_rel.html) method to conduct paired t-test.

Both types of t-tests return a number which is called the **p-value**. If p-value is below 0.05, we can confidently declare the null-hypothesis is rejected and the difference is significant. If p-value is between 0.05 and 0.1, we may also declare the null-hypothesis is rejected but we are not highly confident. If p-value is above 0.1 we do not reject the null-hypothesis.

Read more about the t-test in [this article](http://b.link/test50) and [this Quora](http://b.link/unpaired97). Make sure you understand when to use which type of t-test.

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
import seaborn as sns

### One tailed t-test 
In a packing plant, a machine packs cartons with jars. It is supposed that a new machine will pack faster on the average than the machine currently used. To test that hypothesis, the times it takes each machine to pack ten cartons are recorded. The results, in seconds, are shown in the tables in the file files_for_lab/ttest_machine.xlsx. Assume that there is sufficient evidence to conduct the t test, does the data provide sufficient evidence to show if one machine is better than the other?

#### Import dataset

In [3]:
# Your code here:
data=pd.read_csv(r'C:\Users\Admin\IH-Labs\lab-t-tests-p-values\files_for_lab\ttest_machine.txt')

In [9]:
data['New_machine']=list(map(lambda x: x.split(' ')[0],data['New_machine Old_machine']))

In [11]:
data['Old_machine']=list(map(lambda x: x.split(' ')[1],data['New_machine Old_machine']))

In [13]:
data=data.drop('New_machine Old_machine',axis=1)

In [19]:
for i in data.columns:
    data[i]= pd.to_numeric(data[i], errors='coerce')

In [21]:
# H0 = the mean time of New machine is not shorter than the old machine
# H1 = the mean time of New machine is shorter than the old machine
# significance 5%
st.ttest_ind(data['New_machine'], data['Old_machine'], equal_var=False)
print('p value (single tailed): ',st.ttest_ind(data['New_machine'], data['Old_machine'], equal_var=False)[1]/2)

p value (single tailed):  0.0016211247331589873

In [22]:
# P value is lower than 0.05 that means H0 can be rejected and there are enough evidences to prove that new machine is better than the old one.

#### Import dataset

In this challenge we will work on the Pokemon dataset you have already used. The goal is to test whether different groups of pokemon (e.g. Legendary vs Normal, Generation 1 vs 2, single-type vs dual-type) have different stats (e.g. HP, Attack, Defense, etc.). Use pokemon.csv

In [23]:
# Your code here:
pokemon=pd.read_csv(r'C:\Users\Admin\IH-Labs\lab-t-tests-p-values\files_for_lab\pokemon.txt')

In [25]:
pokemon.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [35]:
pokemon.tail(60)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False
742,674,Pancham,Fighting,NaN,348,67,82,62,46,48,43,6,False
743,675,Pangoro,Fighting,Dark,495,95,124,78,69,71,58,6,False
744,676,Furfrou,Normal,NaN,472,75,80,60,65,90,102,6,False
745,677,Espurr,Psychic,NaN,355,62,48,54,63,60,68,6,False
746,678,MeowsticMale,Psychic,NaN,466,74,48,76,83,81,104,6,False
747,678,MeowsticFemale,Psychic,NaN,466,74,48,76,83,81,104,6,False
748,679,Honedge,Steel,Ghost,325,45,80,100,35,37,28,6,False
749,680,Doublade,Steel,Ghost,448,59,110,150,45,49,35,6,False
750,681,AegislashBlade Forme,Steel,Ghost,520,60,150,50,150,50,60,6,False
751,681,AegislashShield Forme,Steel,Ghost,520,60,50,150,50,150,60,6,False
752,682,Spritzee,Fairy,NaN,341,78,52,60,63,65,23,6,False
753,683,Aromatisse,Fairy,NaN,462,101,72,72,99,89,29,6,False
754,684,Swirlix,Fairy,NaN,341,62,48,66,59,57,49,6,False
755,685,Slurpuff,Fairy,NaN,480,82,80,86,85,75,72,6,False
756,686,Inkay,Dark,Psychic,288,53,54,53,37,46,45,6,False
757,687,Malamar,Dark,Psychic,482,86,92,88,68,75,73,6,False
758,688,Binacle,Rock,Water,306,42,52,67,39,56,50,6,False
759,689,Barbaracle,Rock,Water,500,72,105,115,54,86,68,6,False
760,690,Skrelp,Poison,Water,320,50,60,60,60,60,30,6,False
761,691,Dragalge,Poison,Dragon,494,65,75,90,97,123,44,6,False
762,692,Clauncher,Water,NaN,330,50,53,62,58,63,44,6,False
763,693,Clawitzer,Water,NaN,500,71,73,88,120,89,59,6,False
764,694,Helioptile,Electric,Normal,289,44,38,33,61,43,70,6,False
765,695,Heliolisk,Electric,Normal,481,62,55,52,109,94,109,6,False
766,696,Tyrunt,Rock,Dragon,362,58,89,77,45,45,48,6,False
767,697,Tyrantrum,Rock,Dragon,521,82,121,119,69,59,71,6,False
768,698,Amaura,Rock,Ice,362,77,59,50,67,63,46,6,False
769,699,Aurorus,Rock,Ice,521,123,77,72,99,92,58,6,False
770,700,Sylveon,Fairy,NaN,525,95,65,65,110,130,60,6,False
771,701,Hawlucha,Fighting,Flying,500,78,92,75,74,63,118,6,False
772,702,Dedenne,Electric,Fairy,431,67,58,57,81,67,101,6,False
773,703,Carbink,Rock,Fairy,500,50,50,150,50,150,50,6,False
774,704,Goomy,Dragon,NaN,300,45,50,35,55,75,40,6,False
775,705,Sliggoo,Dragon,NaN,452,68,75,53,83,113,60,6,False
776,706,Goodra,Dragon,NaN,600,90,100,70,110,150,80,6,False
777,707,Klefki,Steel,Fairy,470,57,80,91,80,87,75,6,False
778,708,Phantump,Ghost,Grass,309,43,70,48,50,60,38,6,False
779,709,Trevenant,Ghost,Grass,474,85,110,76,65,82,56,6,False
780,710,PumpkabooAverage Size,Ghost,Grass,335,49,66,70,44,55,51,6,False
781,710,PumpkabooSmall Size,Ghost,Grass,335,44,66,70,44,55,56,6,False
782,710,PumpkabooLarge Size,Ghost,Grass,335,54,66,70,44,55,46,6,False
783,710,PumpkabooSuper Size,Ghost,Grass,335,59,66,70,44,55,41,6,False
784,711,GourgeistAverage Size,Ghost,Grass,494,65,90,122,58,75,84,6,False
785,711,GourgeistSmall Size,Ghost,Grass,494,55,85,122,58,75,99,6,False
786,711,GourgeistLarge Size,Ghost,Grass,494,75,95,122,58,75,69,6,False
787,711,GourgeistSuper Size,Ghost,Grass,494,85,100,122,58,75,54,6,False
788,712,Bergmite,Ice,NaN,304,55,69,85,32,35,28,6,False
789,713,Avalugg,Ice,NaN,514,95,117,184,44,46,28,6,False
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [43]:
pokemon.isna().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False

                    0
#                   1
Name        Bulbasaur
Type 1          Grass
Type 2         Poison
Total             318
HP                 45
Attack             49
Defense            49
Sp. Atk            65
Sp. Def            65
Speed              45
Generation          1
Legendary       False

In [27]:
pokemon['Legendary'].value_counts()

False    735
True      65
Name: Legendary, dtype: int64

#### First we want to define a function with which we can test the means of a feature set of two samples. 

In the next cell you'll see the annotations of the Python function that explains what this function does and its arguments and returned value. This type of annotation is called **docstring** which is a convention used among Python developers. The docstring convention allows developers to write consistent tech documentations for their codes so that others can read. It also allows some websites to automatically parse the docstrings and display user-friendly documentations.

Follow the specifications of the docstring and complete the function.

In [ ]:
def t_test_features(s1, s2, features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']):
    """Test means of a feature set of two samples
    
    Args:
        s1 (dataframe): sample 1
        s2 (dataframe): sample 2
        features (list): an array of features to test
    
    Returns:
        dict: a dictionary of t-test scores for each feature where the feature name is the key and the p-value is the value
    """
    results = {}

    # Your code here
    
    return results

#### Using the `t_test_features` function, conduct t-test for Lengendary vs non-Legendary pokemons.

*Hint: your output should look like below:*

```
{'HP': 1.0026911708035284e-13,
 'Attack': 2.520372449236646e-16,
 'Defense': 4.8269984949193316e-11,
 'Sp. Atk': 1.5514614112239812e-21,
 'Sp. Def': 2.2949327864052826e-15,
 'Speed': 1.049016311882451e-18,
 'Total': 9.357954335957446e-47}
 ```

In [67]:
pokemon_Legen=pokemon[pokemon['Legendary']==True][['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']]
pokemon_non_Legen=pokemon[pokemon['Legendary']==False][['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']]

In [68]:
pokemon_Legen.head()

      HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Total
156   90      85      100       95      125     85    580
157   90      90       85      125       90    100    580
158   90     100       90      125       85     90    580
162  106     110       90      154       90    130    680
163  106     190      100      154      100    130    780

In [69]:
pokemon_non_Legen.head()

   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Total
0  45      49       49       65       65     45    318
1  60      62       63       80       80     60    405
2  80      82       83      100      100     80    525
3  80     100      123      122      120     80    625
4  39      52       43       60       50     65    309

In [82]:
# Your code here

def t_test_features(s1, s2, features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']):
    """Test means of a feature set of two samples
    
    Args:
        s1 (dataframe): sample 1
        s2 (dataframe): sample 2
        features (list): an array of features to test
    
    Returns:
        dict: a dictionary of t-test scores for each feature where the feature name is the key and the p-value is the value
    """

    results = {}
    features1=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']
    for i in features:
        results[i]=st.ttest_ind(s1[i], s2[i], equal_var=False)[1]
    
    # Your code here
    
    return results

In [83]:
# H0: Legendary and non-Legendary pokemons doesn't have significantly different stats on each feature?
# H1: Legendary and non-Legendary pokemons have significantly different stats on each feature?
# significance 5%
t_test_features(pokemon_Legen,pokemon_non_Legen)

{'HP': 1.0026911708035284e-13,
 'Attack': 2.520372449236646e-16,
 'Defense': 4.8269984949193316e-11,
 'Sp. Atk': 1.5514614112239812e-21,
 'Sp. Def': 2.2949327864052826e-15,
 'Speed': 1.049016311882451e-18,
 'Total': 9.357954335957446e-47}

#### From the test results above, what conclusion can you make? Do Legendary and non-Legendary pokemons have significantly different stats on each feature?

In [ ]:
# Your comment here
#P value of each feature is much lower than 0.05, so that means Legendary and non Legendary pokemons have significantly different stats.

#### Next, conduct t-test for Generation 1 and Generation 2 pokemons.

In [85]:
# Your code here
pokemon_G1=pokemon[pokemon['Generation']==1]
pokemon_G2=pokemon[pokemon['Generation']==2]

In [87]:
pokemon_G2.shape

(106, 13)

In [88]:
# H0: Generation1 and Generation2 pokemons doesn't have significantly different stats on each feature?
# H1: Generation1 and Generation2 pokemons have significantly different stats on each feature?
# significance 5%
t_test_features(pokemon_G1,pokemon_G2)

{'HP': 0.14551697834219623,
 'Attack': 0.24721958967217725,
 'Defense': 0.5677711011725426,
 'Sp. Atk': 0.12332165977104394,
 'Sp. Def': 0.18829872292645752,
 'Speed': 0.00239265937312135,
 'Total': 0.5631377907941676}

#### What conclusions can you make?

In [ ]:
# Your comment here
# apart from Speed the p values of all the other features are larger than 0.05.
# That means Generation1 and Generation2 pokemons doesn't have significantly different stats on each feature excpet speed.

#### Compare pokemons who have single type vs those having two types.

In [93]:
# Your code here
pokemon_s_type=pokemon[pokemon['Type 2'].isna()]

In [94]:
pokemon_s_type.shape

(386, 13)

In [95]:
pokemon_d_type=pokemon[~pokemon['Type 2'].isna()]

In [96]:
pokemon_d_type.shape

(414, 13)

In [99]:
t_test_features(pokemon_s_type,pokemon_d_type)

{'HP': 0.11314389855379421,
 'Attack': 0.00014932578145948305,
 'Defense': 2.7978540411514693e-08,
 'Sp. Atk': 0.00013876216585667842,
 'Sp. Def': 0.00010730610934512779,
 'Speed': 0.02421703281819094,
 'Total': 1.1157056505229961e-07}

#### What conclusions can you make?

In [ ]:
# Your comment here
# except HP all the p value of each feature is lower than 0.05.
# That means Single type and two types pokemons doesn't have significantly different stats on each feature excpet HP.

#### Now, we want to compare whether there are significant differences of `Attack` vs `Defense`  and  `Sp. Atk` vs `Sp. Def` of all pokemons. Please write your code below.

*Hint: are you comparing different populations or the same population?*

In [102]:
# Your code here
# H0:  there are not significant differences of Attack vs Defense and Sp. Atk vs Sp. Def of all pokemons
# H1:  there are significant differences of Attack vs Defense and Sp. Atk vs Sp. Def of all pokemons.
# significance 5%
print(st.ttest_rel(pokemon['Attack'], pokemon['Defense'])[1])

1.7140303479358558e-05

In [107]:
st.ttest_rel(pokemon['Sp. Atk'], pokemon['Sp. Def'])[1]

0.3933685997548122

#### What conclusions can you make?

In [ ]:
# Your comment here
# there are significant differences of Attack and Defense but not so much different between Sp. Atk and Sp. Def of all pokemons